#!/bin/bash


echo "Hello World"

read pSize wSize sortAl
echo page $pSize wSize $wSize soring al $sortAl



# if ["$sortAl"]
# make quicksort
# ./quicksort.out $pSize $wSize
# make clean
if [ $sortAl = "quicksort" ]
	then
	echo quicksort
	make quicksort
	./quicksort.out $pSize $wSize

elif [ $sortAl = "heapsort" ]
	then
	make heapsort
	./heapsort.out $pSize $wSize
else
	echo "Unknown Command"
fi

make clean
