#!/bin/bash


echo "Assignment3"
echo "Enter pageSize windowSize sortAl"
read pSize wSize sortAl
echo page $pSize wSize $wSize soring al $sortAl

make clean


if [ $sortAl = "quicksort" ]
	then
	make quicksort
	./quicksort $pSize $wSize

elif [ $sortAl = "heapsort" ]
	then
	make heapsort
	./heapsort $pSize $wSize
else
	echo "Unknown Command"
fi

make clean
