#!/bin/bash


echo "Assignment3"
echo "Enter pageSize windowSize sortAl"
read pSize wSize sortAl
echo page $pSize wSize $wSize soring al $sortAl

make clean

if [ $sortAl = "quicksort" ]
	then
	make quicksort
	./quicksort.out $pSize $wSize

elif [ $sortAl = "heapsort" ]
	then
	make heapsort
	./heapsort.out $pSize $wSize
else
	echo "Unknown Command"
fi

make clean
